/*
 This source file is part of the Swift.org open source project

 Copyright (c) 2025 Apple Inc. and the Swift project authors
 Licensed under Apache License v2.0 with Runtime Library Exception

 See https://swift.org/LICENSE.txt for license information
 See https://swift.org/CONTRIBUTORS.txt for Swift project authors
*/

import Foundation

// MARK: - Entry point

guard CommandLine.arguments.count == 4 else {
    fputs("""
    Usage: GenerateVueResourcesTool <app.js> <app.css> <output.swift>

    Reads the compiled Vue app bundle and stylesheet from the given paths and
    writes a Swift source file that embeds their contents as Data literals inside
    an extension of StaticResources.

    Make sure to run `bin/build-vue-app` before building the Swift package.
    """, stderr)
    exit(1)
}

let jsURL  = URL(fileURLWithPath: CommandLine.arguments[1])
let cssURL = URL(fileURLWithPath: CommandLine.arguments[2])
let outputURL = URL(fileURLWithPath: CommandLine.arguments[3])

// MARK: - Read input files

func read(_ url: URL) -> Data {
    guard let data = try? Data(contentsOf: url) else {
        fputs("""
        error: could not read '\(url.path)'.
        Run `bin/build-vue-app` first to produce the compiled Vue assets.
        """, stderr)
        exit(1)
    }
    return data
}

let jsData  = read(jsURL)
let cssData = read(cssURL)

// MARK: - Generate Swift source

let generated = """
// This file is auto-generated by the GenerateVueResources build tool plugin.
// Do not edit manually — run `bin/build-vue-app` to rebuild the Vue source
// and then rebuild the Swift package to refresh this file.

import struct Foundation.Data

extension StaticResources {

    /// The compiled Vue application bundle that drives interactive documentation
    /// features (navigator sidebar, language toggle, color-scheme toggle).
    static let vueAppScript = File(filename: "app.js", data: Data(base64Encoded: \"\(jsData.base64EncodedString())\")!)

    /// The compiled styles for the Vue application bundle.
    static let vueAppStyleSheet = File(filename: "app.css", data: Data(base64Encoded: \"\(cssData.base64EncodedString())\")!)
}
"""

// MARK: - Write output

do {
    try generated.write(to: outputURL, atomically: true, encoding: .utf8)
} catch {
    fputs("error: could not write '\(outputURL.path)': \(error)\n", stderr)
    exit(1)
}
