/*
 This source file is part of the Swift.org open source project

 Copyright (c) 2021 Apple Inc. and the Swift project authors
 Licensed under Apache License v2.0 with Runtime Library Exception

 See https://swift.org/LICENSE.txt for license information
 See https://swift.org/CONTRIBUTORS.txt for Swift project authors
*/

import Foundation

import XCTest
@testable import SwiftDocC

class VersionTripletTests: XCTestCase {
    func testComparable() {
        XCTAssertLessThan(VersionTriplet(0,0,0), VersionTriplet(0,0,1))
        XCTAssertLessThan(VersionTriplet(1,0,0), VersionTriplet(1,0,1))
        XCTAssertLessThan(VersionTriplet(1,1,0), VersionTriplet(1,2,1))
        XCTAssertLessThan(VersionTriplet(1,1,0), VersionTriplet(1,1,2))
        XCTAssertLessThan(VersionTriplet(1,1,1), VersionTriplet(1,1,2))
        XCTAssertLessThan(VersionTriplet(5,0,0), VersionTriplet(10,0,1))
        
        // Test the autogenerated equality conformance for coherence
        XCTAssertEqual(VersionTriplet(5,2,1), VersionTriplet(5,2,1))
    }
    
    func testStringRepresentation() {
        let oneComponent = VersionTriplet(1, 0, 0)
        
        XCTAssertEqual(oneComponent.stringRepresentation(precisionUpToNonsignificant: .minor), "1.0")
        XCTAssertEqual(oneComponent.stringRepresentation(precisionUpToNonsignificant: .patch), "1.0.0")
        XCTAssertEqual(oneComponent.stringRepresentation(precisionUpToNonsignificant: .all), "1.0.0")
        
        let twoComponents = VersionTriplet(1, 2, 0)
        XCTAssertEqual(twoComponents.stringRepresentation(precisionUpToNonsignificant: .minor), "1.2")
        XCTAssertEqual(twoComponents.stringRepresentation(precisionUpToNonsignificant: .patch), "1.2.0")
        XCTAssertEqual(twoComponents.stringRepresentation(precisionUpToNonsignificant: .all), "1.2.0")
        
        let threeComponents = VersionTriplet(1, 2, 3)
        XCTAssertEqual(threeComponents.stringRepresentation(precisionUpToNonsignificant: .minor), "1.2.3")
        XCTAssertEqual(threeComponents.stringRepresentation(precisionUpToNonsignificant: .patch), "1.2.3")
        XCTAssertEqual(threeComponents.stringRepresentation(precisionUpToNonsignificant: .all), "1.2.3")
        
        let zeroVersion = VersionTriplet(0, 0, 0)
        XCTAssertEqual(zeroVersion.stringRepresentation(precisionUpToNonsignificant: .minor), "0.0")
        XCTAssertEqual(zeroVersion.stringRepresentation(precisionUpToNonsignificant: .patch), "0.0.0")
        XCTAssertEqual(zeroVersion.stringRepresentation(precisionUpToNonsignificant: .all), "0.0.0")
        
        let zeroMinorVersion = VersionTriplet(1, 0, 1)
        XCTAssertEqual(zeroMinorVersion.stringRepresentation(precisionUpToNonsignificant: .minor), "1.0.1")
        XCTAssertEqual(zeroMinorVersion.stringRepresentation(precisionUpToNonsignificant: .patch), "1.0.1")
        XCTAssertEqual(zeroMinorVersion.stringRepresentation(precisionUpToNonsignificant: .all), "1.0.1")
    }
}
