/*
 This source file is part of the Swift.org open source project

 Copyright (c) 2021 Apple Inc. and the Swift project authors
 Licensed under Apache License v2.0 with Runtime Library Exception

 See https://swift.org/LICENSE.txt for license information
 See https://swift.org/CONTRIBUTORS.txt for Swift project authors
*/

public import SwiftDocC
public import Foundation

/// The result of executing an action.
public struct ActionResult {
    /// Problems found while trying to perform the action.
    public var problems: [Problem]
    
    /// Outputs generated by the action, if any.
    public var outputs: [URL]

    /// If an error was encountered during the action.
    public var didEncounterError: Bool
    
    /// Creates a new action results with a flag indicating if an error occurred during the action and any URLs
    /// the action generated.
    ///
    /// - Parameters:
    ///   - didEncounterError: A Boolean value indicating if an error occurred during the action.
    ///   - outputs: The URLs generated by the action this result represents.
    public init(didEncounterError: Bool = false, outputs: [URL] = []) {
        self.problems = []
        self.outputs = outputs
        self.didEncounterError = didEncounterError
    }
}
