/*
 This source file is part of the Swift.org open source project

 Copyright (c) 2026 Apple Inc. and the Swift project authors
 Licensed under Apache License v2.0 with Runtime Library Exception

 See https://swift.org/LICENSE.txt for license information
 See https://swift.org/CONTRIBUTORS.txt for Swift project authors
*/

import Foundation
import Markdown

/// A checker that warns when a level-2 section heading differs only in casing from a recognized DocC section heading.
struct MiscasedSectionHeading: Checker {
    static let expectedHeadings = ["See Also", "Topics", "Overview", "Discussion"]

    /// Miscased headings paired with their respective expected heading.
    var miscasedHeadings: [(heading: Heading, expectedHeading: String)] = []

    var diagnostics: [Diagnostic] {
        return miscasedHeadings.compactMap { miscased -> Diagnostic? in
            guard let headingRange = miscased.heading.range else { return nil }
            let actual = miscased.heading.plainText
            let expected = miscased.expectedHeading

            return Diagnostic(
                source: sourceFile,
                severity: .warning,
                range: headingRange,
                identifier: "MiscasedSectionHeading",
                // In English, the article for a word depends on the word's pronunciation, not its spelling.
                // "An" is used before a vowel sound, and "a" before a consonant sound.
                // Only the "Overview" heading starts with a vowel sound.
                summary: "Level-2 heading '\(actual)' does not form \(expected.first == "O" ? "an" : "a") \(expected) section; did you mean '\(expected)'?",
                explanation: """
                DocC matches the section headings 'See Also', 'Topics', 'Overview', and 'Discussion' case-sensitively. \
                A heading whose casing doesn't match exactly isn't recognized as that section. For example, an authored \
                '## See also' renders as a regular heading and an autogenerated 'See Also' section appears alongside it.
                """,
                solutions: [
                    Solution(
                        summary: "Replace '\(actual)' with '\(expected)'",
                        replacements: [.init(range: headingRange, replacement: "## \(expected)")]
                    ),
                ]
            )
        }
    }

    private var sourceFile: URL?

    init(sourceFile: URL?) {
        self.sourceFile = sourceFile
    }

    mutating func visitHeading(_ heading: Heading) {
        guard heading.level == 2 else { return }
        if let expected = Self.expectedHeadings.first(where: { $0.lowercased() == heading.plainText.lowercased() }),
           expected != heading.plainText {
            miscasedHeadings.append((heading, expected))
        }
    }
}
